### ISSUE TITLE
本地部署

### ISSUE THREAD

**Issue by mlpyw** [jinmingyi1998/OnlineJudge#4]
你好，想问一下在本地部署怎么弄，还有就是二次开发

**Comment by jimmy-evo** [comment]
本地部署推荐使用docker compose

二次开发修改好代码build对应镜像即可

**Comment by mlpyw** [comment]
我看你的判题服务器是另一个？？/

**Comment by mlpyw** [comment]
我看你的判题服务器是另一个？？/

**Comment by mlpyw** [comment]
是不是有接口文档的

**Comment by jimmy-evo** [comment]
判题由[判题服务](https://github.com/jinmingyi1998/JudgerServer)完成。并将结果发送给回调

**Comment by mlpyw** [comment]
sql文件有吗？还是要自己创建数据库？

**Comment by jimmy-evo** [comment]
> sql文件有吗？还是要自己创建数据库？

从空数据库启动，只需创建database。 启动server会自动初始化tables

**Comment by mlpyw** [comment]
表结构需要自己弄吗？

**Comment by mlpyw** [comment]
好的，谢谢

**Comment by mlpyw** [comment]
redis是不是也一样的，只需要连接即可

**Comment by jimmy-evo** [comment]
> redis是不是也一样的，只需要连接即可

对的。 可以参考配好的docker compose
